# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  api-gateway:
    image: traefik:v3.2@sha256:e561a37f8710d9cf41c78bdf421d822b2c0b48267ec0552e644565fb55466ea9
    ports:
      - 8080:8080
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    depends_on:
      - auth
      - chatbot-api
      - chatbot-evaluate-api
      - chatbot-index-api

  auth:
    image: ghcr.io/pagopa/dos68k/auth:latest@sha256:df3e35c9f00ab22ef7ca8a074906c2a8c116bebe696a632047cc9fb6c670dda2
    env_file:
      - ./auth/.env
    ports:
      - 3000:3000

  chatbot-api:
    image: ghcr.io/pagopa/dos68k/chatbot-api:latest@sha256:3ad586259b72e79f4bdf1df4726f39b4263a5fab4351b269d9da6eaa35ff3dc8
    env_file:
      - ./chatbot-api/.env
    ports:
      - 8000:8000
    # Uncomment the volumes below to mount custom RAG tool configs or a custom agent config.
    # See chatbot-api/README.md#customization for details.
    # volumes:
    #   - ./chatbot-api/scripts/tool_config:/app/src/modules/chatbot/tool/config
    #   - ./my-agent.yaml:/app/src/modules/chatbot/agent/agent.yaml
    depends_on:
      - localstack
      - masking
      - redis-vdb
      - qdrant

  chatbot-evaluate-api:
    image: ghcr.io/pagopa/dos68k/chatbot-evaluate-api:latest@sha256:c9aca87ae3b541ad1d72fd3eacc29968b9ef3ed28f979598f0976f2146fd238e
    env_file:
      - ./chatbot-evaluate/api/.env
    ports:
      - 8002:8000
    depends_on:
      - redis-queue
      - redis-vdb
      - localstack

  chatbot-evaluate-worker:
    image: ghcr.io/pagopa/dos68k/chatbot-evaluate-worker:latest@sha256:cde37219f5148ce58277d0d40c21f99258027fd99694f579fa2bf34075be7831
    env_file:
      - ./chatbot-evaluate/worker/.env
    depends_on:
      - redis-queue
      - localstack

  chatbot-index-api:
    image: ghcr.io/pagopa/dos68k/chatbot-index-api:latest@sha256:8c057c3ce5eb945d3682d987272438310fbf3327dbe1d1d70472a3038302a6a2
    env_file:
      - ./chatbot-index/api/.env
    ports:
      - 8003:8000
    depends_on:
      - redis-queue
      - minio
      - redis-vdb
      - qdrant
      - localstack
      - chatbot-index-worker

  chatbot-index-worker:
    image: ghcr.io/pagopa/dos68k/chatbot-index-worker:latest@sha256:3e444a51da9ef691752db2204a505d80216398fc512f6647a6f9583037c5e85a
    env_file:
      - ./chatbot-index/worker/.env
    depends_on:
      - redis-queue
      - minio
      - redis-vdb
      - qdrant
      - localstack

  masking:
    image: ghcr.io/pagopa/dos68k/masking:latest@sha256:8f6cdfc925bfdb62934266f0831de3a54e975ed004f93128f13883e72005bac5
    ports:
      - 3001:3000

  frontend:
    image: ghcr.io/pagopa/dos68k/frontend:latest@sha256:b1cd3b838759d4ddf9d54fd733d434219ce01ea1c2af1633e36f16555759a0b6
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    ports:
      - 80:80
    depends_on:
      - api-gateway

  # db:
  #   image: postgres:17
  #   restart: always
  #   shm_size: 128mb
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env.database
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U user -d db"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  minio:
    image: minio/minio:latest@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    env_file:
      - ./.env.storage

  redis-vdb:
    image: redis/redis-stack:7.4.0-v8@sha256:5d5154123426693540ea6c1d9e638eae2bf2024879c839db6fcfdd7717e817c7
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_vdb_data:/data

  qdrant:
    image: qdrant/qdrant:latest@sha256:b3063c673f3973877c038eeecc392bad5011f072ee7892b56c9a8e204a3bdea9
    container_name: qdrantdb
    ports:
      - 6333:6333
    volumes:
      - qdrant:/qdrant_storage

  redis-queue:
    image: redis:8.4@sha256:b69f2ae9adef7d679fc7cace28e1d4d7e0359b1341861a55995aef5d1b285166
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  langfuse-worker:
    image: docker.io/langfuse/langfuse-worker:3.115@sha256:c9dc71559f880bc82d7087ca6515b66ddf904dbf209ea578ea5fa17cd64b6ab0
    ports:
      - 3030:3030
    env_file:
      - ./.env.langfuse
    depends_on:
      - db
      - minio
      - valkey
      - clickhouse

  langfuse-web:
    image: docker.io/langfuse/langfuse:3.115@sha256:48c51b585350a9de1e904df9410f5507afbfd94c079cf23efec1abf242c6f414
    ports:
      - 4001:3000
    env_file:
      - ./.env.langfuse
    depends_on:
      langfuse-worker:
        condition: service_started
      db:
        condition: service_healthy

  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:25.8.8.26-alpine@sha256:68b9d9eb4cb949a03d1f90b76fd8d396a5999dd57ba1ee914ea36c77716ce937
    user: "101:101"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - langfuse_clickhouse_data:/var/lib/clickhouse
      - langfuse_clickhouse_logs:/var/log/clickhouse-server
    ports:
      - 8123:8123
      - 9002:9000

  valkey:
    image: valkey/valkey:8.1.4-alpine3.22@sha256:e706d1213aaba6896c162bb6a3a9e1894e1a435f28f8f856d14fab2e10aa098b

  localstack:
    image: localstack/localstack@sha256:a3517e7b7c14780b755a0b1160b2770e2968ca2f4fbb355877b2b303f6d65033
    ports:
      - 4566:4566
    env_file:
      - ./.env.localstack
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/init/ready.d:/etc/localstack/init/ready.d

volumes:
  langfuse_clickhouse_data:
    driver: local
  langfuse_clickhouse_logs:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  redis_vdb_data:
    driver: local
  db_data:
    driver: local
  qdrant:
    driver: local
  localstack:
    driver: local
