blank_issues_enabled: false

contact_links:
  - name: Questions and discussions
    url: https://github.com/pagopa/DOS68k/discussions
    about: Use GitHub Discussions for questions, ideas, governance topics, and broader conversations.

  - name: Code of Conduct
    url: https://github.com/pagopa/DOS68k/blob/community/CODE_OF_CONDUCT.md
    about: Please read the Code of Conduct before participating in the project.
